christfellowshipchurch/apollos-api

- src/data/website-pages-content-item/data-source.js
- src/data/website-pages-content-item/resolver.js
- src/data/website-pages-content-item/schema.js
Update the query for getting Web Pages to respect the Item's Url Slugs set in Rock. The item must be both in the correct Content Channel for Web Pages and also have a Url Slug set in Rock
> Updated getWebsitePageContentByTitle

- config.yml
- src/data/content-item/resolver.js
- src/data/content-item/schema.js
- src/data/index.js
- src/data/website-html-content-item/data-source.js
- src/data/website-html-content-item/index.js
- src/data/website-html-content-item/resolver.js
- src/data/website-html-content-item/schema.js
Added `website-html-content-item`
This item was created to just pass HTML from Rock and reuses the `content-item` resolvers and schema.
> [CFDP-429] website-html-content-item

- src/data/content-item/resolver.js
- src/data/event-content-item/resolver.js
- src/data/sanitize-html.js
The `apollos-data-connector-rock` was sanitizing the htmlContent removing the `target` attribute in `<a>` tags removing the ability to open links in a new tab from the HTML content.
Override htmlContent in the **resolvers** to use a custom `sanitizeHtml` for `content-item` and `event-content-item`. Allowing the `target` attribute in `<a>` tags.
> Added Custom sanitize-html.js

- src/data/utils.js
* API was misreading url as a guid in the `createVideoUrlFromGuid` method and creating bad urls.
###
* Updated `createVideoUrlFromGuid` method to look for 'http'., instead of splitting string with '-'.
> [CFDP-526] Video Url Bug Fix

- src/data/campus/data-source.js
- src/data/campus/resolver.js
Changed campus pastor email to use email from `leaderPersonAliasId`, instead of generating them manually. This solves for the incorrect campus pastor email bug.
> Campus Pastor Email

- config.yml
- package.json
- src/data/auth/resolver.js
- src/data/auth/schema.js
- src/data/index.js
- src/data/stream-chat/data-source.js
- src/data/stream-chat/index.js
- yarn.lock
Takes the core of @asleepingpanda 's POC work on branch [chat-discovery](https://github.com/christfellowshipchurch/apollos-api/compare/chat-discovery) and alters it to be production ready.
**Specifically, this PR:**
- Adds `stream-chat` dependency
- Adds a feature flag `LIVE_STREAM_CHAT`, accessible only to users in the security group **CFDP Experimental Features** (`1014843`)
- Creates `src/data/stream-chat` to manage `StreamChat` client instance
- Creates `streamChatToken` query resolver on `AuthenticatedUser`
|**The new resolver in action**|
|---|
|![CleanShot 2020-08-26 at 00 05 18@2x](https://user-images.githubusercontent.com/1812955/91254783-3d88a300-e731-11ea-84ad-24ff9bc6161e.jpg)|
**Setup**
New `.env` variables are required to initialize the `StreamChat` client.
The keys are:
``` …
```
> Create AuthenticatedUser.streamChatToken resolver

- src/data/auth/resolver.js
- src/data/auth/schema.js
- src/data/stream-chat/data-source.js
**Summary**
This PR adds a new field/query to  `AuthenticatedUser` to return the chat role for the current user (for the given channel). It:
1. Determines if the user is in the configured Security Group for chat moderators.
1. If so, adds the user as  a moderator to the channel in Stream.io, so that the user can make moderation calls in the client.
1. Returns the role to the client, so that the client can update the UI and make moderation calls.
**Discussion**
- There are only two roles returned right now, `MODERATOR` and `USER`. Made this an enum  type so that we can add other roles, e.g. `ADMIN`.
- Right now, a user is globally a moderator or not. We added a content ID param so that, in the future, we could look up the event for a security group attribute and have _event-specific_ …
> [Chat] Add authenticatedUser.streamChatRole field and resolver

- src/data/groups/data-source.js
- src/data/groups/schema.js
@burkeshartsis this update matches the `resources` schema to the same Feature Action schema in order to make routing more cohesive on the app.
This PR completely deprecates the OG `resources` schema, but I'm down to keep that supported if need be for the web stuff.
Thoughts?
> Uses Feature Action schema for Groups Resources

- package.json
- src/data/live-stream/resolver.js
- src/data/live-stream/schema.js
- yarn.lock
**Summary**
This PR adds a new field to the `LiveStream` type called `chatChannelId`. This moves the channel ID generation from the client to the server, giving us more flexibility in the future should we decide to change the logic. For example, if this isn't unique enough, we can fix it without a new client. Or if livestreams get a proper node ID, we can start using that same value for this field.
**Discussion**
I'm SHA1 hashing the livestream parent ID (e.g. `EventContentItem:1e07e4f2e1b52807e43b2338c73d88ba`), the livestream start time and the end time. SHA1 guarantees some kind of mathy uniqueness and a fixed length.
**Testing**
GraphQL Playground (you may need to be authenticated):
```gql
query getLiveContent {
liveStreams {
isLive
media {
sources {
uri
}
}
chatChannelId
contentItem …
```
> [Chat] Chat Channel ID and Event Metadata

- src/data/live-stream/schema.js
Add InteractionActions to enum for live-stream.
This PR needs this change. https://github.com/christfellowshipchurch/apollos-app/pull/164
> Setup Live Stream Interactions

- config.yml
- src/data/auth/resolver.js
- src/data/stream-chat/data-source.js
- [**🏕 Make a chat moderator Security Group in Rock**](https://3.basecamp.com/3926363/buckets/17566548/todos/3098262058)
- [**🏕 [API] Create GROUP_CHAT Feature flag**](https://3.basecamp.com/3926363/buckets/17566548/todos/3115906311)
- Defines a global moderator security group ID for livestream events
- Slight refactor of resolver for `AuthUser.streamChatRole`
- Pushes logic out of core `resolver` into `data-source`
- Makes methods more flexible, in anticipation of usage for Group Chat
- Add `GROUP_CHAT` feature flag
You can do the testing via graphql playground locally (http://localhost:4000/graphql)
Copy the `token` value from the response of this query:
```graphql
mutation authenticate($identity: String!, $password: String!) {
authenticate(identity: $identity, password: $password) { …
```
> [Chat] Add moderator security group and GROUP_CHAT feature flag

- src/data/checkinable/data-source.js
- src/data/live-stream/data-source.js
There was an issue where the API was looking for a property on a null value.
This was caused by the _old_ way of handling Check In for Event Content Items. I've now updated this query to load in the new CheckInable method and it loads up just fine in the app, now.
> Updates Check In for Event Content Items

- src/data/group-item/data-source.js
- src/data/schedule/data-source.js
Fixes a bug currently happening with the 3x test groups that I'm in (Brandi's Tech, CFDP Testing, Brandi's Large Revelation) where due to some unknown reason, the group's `schedule` cannot be found so `occurrences` cannot be determined.
They're assumed to be there, so resolving `dateTime` fails and throws a 500 error.
The UI/client effect of this is that the **web** groups list page and individual pages won't load, and individual group detail views on **app** break as well.
Also fixes a copy/paste issue with the caching mechanism for `Schedules` so the result gets stored properly.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/1812955/98020897-9a5ba600-1dd1-11eb-9aca-79923c8ed8c9.png)|![image (7)](https://user-images.githubusercontent.com/1812955/98021017-c1b2 …
> [GroupItem] Fix resolution of GroupItem.dateTime when missing schedule

- config.yml
- src/data/features/data-source.js
- src/data/utils.js
Quick gut check on this PR!
This PR enables a bunch of new UI Elements on the 5.4.0 update. These UI elements are "version flagged" meaning that they require a mobile client of at least 5.4.0 or later to show.
The PR does not immediately enable these UI elements, but rather links up the elements to Rock in order to allow for CM's to enable it at their will.
1. Horizontal Card List Feed Feature
2. Action Bar updates for Give Feed
3. Action Bar url update for Profile Feed
> Content prep client 5.4.0

- .prettierrc.json
- src/data/defined-value-list/data-source.js
- src/data/event-content-item/resolver.js
- src/data/event-content-item/schema.js
- src/data/features/schema.js
- src/data/live-stream/resolver.js
- src/data/live-stream/schema.js
- src/data/website-content-item/schema.js
This PR adds actions to live streams. You need an active live stream and a live stream action on your event in Rock to test. I quickly added one and then removed it to test earlier. This is not altering an existing logic just adding actions to the live stream resolver.
Here is what a potential query might look like.
> Add liveStreamActions to live stream

- src/data/live-stream/data-source.js
- src/data/schedule/data-source.js
***Fix to some time zone inconsistencies specifically within the parseiCalendar method***
Before parsing the iCal object, we need to find and replace the start and end data/time with one that specifies the current timezone of the event
Rock returns a DTSTART/DTEND in the following format: DTSTART:20200419T171500 which is ambiguous to the time zone, so node-ical will pick the locale of the current machine in which the program is running.
When an event starts, the offset for the first date instance is what the parser uses for _all_ dates. This would mean that a repeated event set up before DLS would have an offset of -4 that carries with it into DLS. 
Ex: 4pm before DLS becomes 3pm after DLS
Instead of using the "relative" time zone identifier (America/New_York), we calculate the current …
> Read the comments for a better description

- src/data/content-item/data-source.js
- src/data/group-item/data-source.js
- src/data/live-stream/data-source.js
- src/data/live-stream/resolver.js
- src/data/live-stream/weekend-services.js
In order to help mitigate the load issues that we were seeing, this PR does a couple of things
* On Saturday and Sunday, no requests are made to Rock to check and see if a Live Stream is active
* Best practices implemented for a couple of Redis requests
* Cached `getRelatedNodeById`
* On Live Stream Actions, return `[]` if id is null or an empty string
[Loom Demo](https://www.loom.com/share/7f237c77b7c44cd0ae074302f308cc46)
> Hard code weekend schedules

- src/data/live-stream/schema.js
Adds a new action type to the interaction enum for live stream actions
Fire up the web-app on the `add-live-stream-action-interaction` branch and go to a live stream and click on an action. It should fire off the interactWithNode with the action of VIEWED_ACTION. We should also be able to see the interaction recorded in Rock.
**Manual QA**
> Add VIEWED_ACTION to interaction enum

- src/data/content-item/data-source.js
- src/data/live-stream/data-source.js
- src/data/page-builder/data-source.js
In order to mitigate some unnecessary traffic to Rock, we introduced a 15 minute Redis cache for all Content Items. 
This PR expands on that by introducing a new request builder method `byAttributeValue` that is used by Live Streams and Page Builder.
The Apollos API will hit Rock and fetch Content Items by the value of an Attribute, then cache the value in Redis for reuse.
> Content item caching

- src/data/schedule/data-source.js
- src/data/url/data-source.js
Fixes an issue where Groups with no schedule were not getting filtered out, but rather returning with "TODAY" being the date
Groups were not filtering correctly
There was an issue where a null check wasn't happening with `moment` and it was instead just defaulting to today instead
> [CFDP-1077] Schedule filter error

- src/data/checkinable/data-source.js
Resolves an issue where users get cheked in, but the app still displays them as not checked in
When people have too many Person Alias Ids, the request URL becomes too large for Rock
If someone has an attendance record in Rock for a non-primary alias id, they won't be considered checked in. This _could_ potentially cause some false negatives, although attendance records triggered from the app will save to the person's _primary_ alias id, so we should be safe
> [CFDP-1167] User Check In Bug

- src/data/group-preferences/data-source.js
There are ultra-high res cover image assets used in Rock for **Preference** and **SubPreference** `DefinedTypes`.
This PR uses the `rockImageUrl` method to transform the URL returned to clients, so they are shrunk down to smaller and optimized versions.
None
Run the following query in graphql, and verify there are transform parameters returned in the `coverImage.sources[0].uri` value (like `&w=768&quality=70&format=jpeg`)
```graphql
query preferencesAndSubPreferences {
allPreferences {
id
title
summary
coverImage {
sources {
uri
}
}
}
allSubPreferences {
id
title
summary
coverImage {
sources {
uri
}
}
}
}
```
None
**Manual QA**
> Use smaller preference and subPreference cover images

- src/data/group-item/data-source.js
This PR makes it so we index the full name of the day a group meets. If a user types `Monday` or anything shorter in the search they will get a match. Just indexing `Mon` in Algolia would not allow a user to get a match by typing `Monday`.
This will take effect the next time we index Algolia.
**Manual QA**
> Index full day in group index

- src/data/checkinable/data-source.js
- src/data/group-item/resolver.js
- src/data/schedule/data-source.js
* video calls require a user to be logged in to access
* video calls only show when the group is currently active
* duration of the Group is defaulted to 4 hours from the start time
Group Video buttons should only be visible when the Group is currently meeting
Groups in Rock don't have a duration, so we've defaulted the duration to 4 hours from the start time of the group
Query for a bunch of Groups to see if the video calls show up as expected
n/a
> [CFDP-1191] Filters when Zoom Buttons show up

- src/data/group-item/data-source.js
Groups were being queried with an array of Group Types that were not unique. This meant that a Group Type Ids array could look like [1, 1, 1, 1, 1, 1, 1, 1] in which the exact same groups were queried and returned multiple times.
This caused extensive loading times and extra strain on Rock. This has been resolved by making sure that the Group Type Ids array that's returned is a unique array.
> [CFDP-1203] Group Duplication

- src/data/content-item/data-source.js
The `sortByAssociationOrder` method seemed to be breaking for pages using the Page Builder content items that returned a null `childContentChannelItemId`. I added a catch for it.
Go to `/jupiter-plan-your-visit` page that was previously breaking on master.
**Manual QA**
> [CFDP-1251] Fix for Page Builder Bug

- src/data/group-item/data-source.js
- src/data/url/data-source.js
- src/data/url/resolver.js
closes: #228 
This [PATCH](https://github.com/christfellowshipchurch/apollos-api/commit/a23153a916109770e2934ae5057d5443688a755b) broke deleting resources. 
@asleepingpanda do you have a suggestion on how to fix this, but also address your PATCH changes? We need the TargetEntityId as the id to be able to delete the resource.
> Fix groups resources delete

- src/data/url/data-source.js
There is a phantom bug out right now where people updating from mobile app v5.4.0 --> v6.0.0 are getting a "white screen of death" when navigating to the Give screen.
What I noticed was that the 1.0 and 2.0 API's are returning different Id's for the same Url. 
For example:
Given the Url: https://cf.church/pushpay?feed=give
V1 API Node Id: `Url:00f6c0472e9887c9a2e494f04992ce8a41543e8160a5195f738931b99ae6f3c2a8a0a3aaffa54f5ce8efe95b70a081cb`
V2 API Node Id: `Url:f4974a223763b3a06ea2cd73ff30952be89d6281e05bc41f7ee423cd227a2b008149a76a099525a2281fbe97f73d11782cdbcae8821e26fa417069f1368ec6d8cc0ef4040d2f2e617c9d5192457c82a7d8603ba7b623bee8863c730a7fa1dfaa74936570206d0917e4feb0d71dc6617a6249eeca3a2f250e668315346de25e32dc5bf9c46ca5f971c1abca71348c34fe03854c9a8765238cfb61988ada8f4996`
Run a `node` …
> Check root of Url id before attempting to parse the id

- src/data/group-item/data-source.js
- src/data/stream-chat/data-source.js
Closes #233 
Closes #235 
Add meta data on group chat channels for `lastSyncedWithRockAt`. The intention is to limit the costly operation of fetching all members and leaders and add/removing/promoting/demoting everyone in the group chat channel as needed. This currently happens every request for a group's `streamChatChannel` node, but this PR modifies it to happen at most once per 24hrs.
Should also fix a sneaky bug (or potential/inevitable bugs) around updating channels after they've been created, i.e. managing the array of users who have muted notifications.
Removes the `GROUP_CHAT` feature flag checks since it's technically live now.
For development and testing, I used a hard coded channel ID that was easy to find in [our Stream …
> Group chat data syncing cleanup

- src/data/url/data-source.js
When a user adds a url, they don't know to add the http protocol to the beginning of the string and it ends up messing up routing on the website. 
It's a rudimentary and immature path, but it works for this specific use case. Before posting a Url to Rock, we will update the url to include `https://` at the beginning of the string if it doesn't exist already.
> Enforces an http protocol at the beginning of the url string

- src/data/group-item/data-source.js
- src/data/group-item/resolver.js
- src/data/group-item/schema.js
- src/data/search/search-index.js
A performant way to qualify what subPreferences a preference has, instead of querying all groups and filtering.
This is needed for only showing relevant lineup type. See PR https://github.com/christfellowshipchurch/web-app-v2/pull/175
query
```
query getGroupFacetFilters {
groupFacetFilters(facet: "subPreference", facetFilters: ["preference:Crew"])
}
```
return
```
{
"data": {
"groupFacetFilters": [
"Pray Together",
"Study Together"
]
}
}
```
**Manual QA**
> Add group facet filters

- src/data/content-item/data-source.js
CM's didn't like that auto-generated summaries were being created. If they don't include a summary in Rock, no summary should be seen
This is a global change that will effect all content items
Test out a Content Item that doesn't have a summary included
> Patch update summary

- config.yml
- src/data/page-builder/data-source.js
Introduces a new `/studies` route for a Content Channel specifically holding Studies & Series. This is primarily used for Groups, but needs to be available site-wide
[CFDP-1396]
[CFDP-1396]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1396
> Add Content Channel route for /studies

- src/data/features/data-source.js
Content Managers requested the ability to create a Content Block that just contained an Image and no additional text content.
This could have been added as a part of the resolver, but for right now, it's only needed when a Content Manager manually selects the "Hide a Title" option on a _Content Item_ inside of Rock. For this reason, I opted to enable this in the `createContentBlock` method in the datasource and _not_ make it a global resolver update.
I've attached 2 screenshots of a "before" and "after" using a Content Block inside of Rock with this feature enabled
Before
After
[CFDP-1412]
[CFDP-1412]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1412
> Hide Title from Content Block

- src/data/content-channel/data-source.js
- src/data/features/resolver.js
It enables the Primary Action to show up on the Hero List and Horizontal Card List Feature. This will _only_ show up when the `actions` or `cards` is greater than 3. This is so that we can show the "See more" button on the Feature that takes them to a collection of _all_ children for the parent Content Item.
The Primary Action should be calculated and returned as a finalized object wherever the Feature is being created.
The "filtering" of the primary action based on the number of cards is done on the `resolver`. This is to avoid needing to use extensive logic within the data source method that creates each Feature to wait for the algorithms to run.
The only consequence of this, though, is that the filtering logic is universal and will need to be rethought it we end up finding additional …
> Enables the "Primary Action" for Features

- src/data/group-item/jobs.js
Quick tweak to reduce Group Finder data indexing on the Staging environment to only M/W/F instead of every day.
None
Carefully read through the code 🤷‍♂️  and gut check my cron schedule syntax [with a reference cheat sheet](https://www.adminschoice.com/crontab-quick-reference).
None
**Manual QA**
> Use less frequent schedule for Group Item indexing on staging

- src/data/additional-endpoints/resolver.js
- src/data/additional-endpoints/schema.js
Temporary endpoint for getting a collection of buttons from ALL content types.
To be replaced by a more robust solution in the future, I'm sure, but for right now it works.
> Endpoint to get a collection of FeatureActions for Node Id

- src/data/group-item/jobs.js
Fixes #266
Bull cron jobs are being considered "stalled" because they don't respond for < 30s.
This allows up to 2min for a job to complete before counting it as stalled.
N/A
YOLO
N/A
**Manual QA**
> Increase stalled interval time for Group Item Bull queues

- src/data/group-item/data-source.js
- src/data/group-item/resolver.js
- src/data/group-item/schema.js
Schema updates …
152b8ac
* New enum for Group Member Status
OPEN : group can be joined
FULL : group cannot be joined
MEMBER : user is already a member/leader of the group
PENDING : user's member status is pending
* New endpoint for determining a user's status based on the Group Id
Because this experience is still very new/thrown together last minute, I opted in for a very explicit, low impact way of getting this status. This way we can rip it out much more easily than if it were a first-party field on the Group
------------------------------------------------------------------------------------
Add Group Member Status Logic …
8d62ad5
* Resolver for the schema query
* Logic for actually getting the status of a Group for the interested member
* When attempting to contact a leader/add a …
> Group member status

- src/data/content-item/jobs.js
- src/data/group-item/jobs.js
Updates the schedules for indexing Groups and Content Items, so they don't overlap and occur less often on staging environment.
None
Whenever we change the indexing schedules, we need to delete the old ones first. I haven't figured out how to surgically clear _only_ the upcoming scheduled jobs, while preserving past job success/fail history. So I'll open a follow up PR that removes the `deleteJobs()` lines so API deployments don't needlessly throw away job success/fail history.
> Refine indexing schedules and manual trigger

- src/data/action-algorithms/data-source.js
If a person does not have any groups, we'll create a card that redirects the user to the Group Finder
> Implements a default card for Groups

- src/data/content-item/resolver.js
- src/data/group-item/data-source.js
- src/data/search/search-index.js
Closes #216 by forwarding the current `userToken` along with the two most important Algolia search paths: Group Finder and Discover.
There are "peripheral" searches like getting the facet options for group finder that were purposefully omitted/not given the `userToken`, as I think that will needlessly muddy analytics later. I feel the most value is in searches where text/filters were manually input, rather than "hidden" searches used to drive UI options without user interaction.
Perform content and group searches as an authenticated user and non-authenticated.
They should all work as expected.
Unfortunately there's a bit of a delay on Algolia dashboard, so you can see the `userToken` value being sent by adding a `console.log` in the `byPaginatedQuery` method of `SearchIndex` class …
> Algolia user token

- config.yml
- src/data/content-item/data-source.js
- src/data/page-builder/data-source.js
When creating a Vertical Card List feature on Content Item features, we will check attribute values to see if the `title` should be hidden. If so, we return the `title` as `null`.
We only do this check on Feature Feeds generated by the `ContentItem.getFeatures` data-source method. This is so that we don't mess up any of the explicit Feature Feeds (ex. Home, Events, Give, etc), but instead only give the option for a feature on a "Page Builder" page.
> Patch hide title content categories

- src/data/stream-chat/data-source.js
This PR fixes the `muteNotifcations` object from stream and makes sure it pulls in the correct attribute.
> Mute Notifcations with Stream

- src/data/stream-chat/data-source.js
* Backwards compatibility deemed unnecessary per OneSignal documentation
> Removes backwards compatibility
