christfellowshipchurch/apollos-api

src/data/website-content-item/resolver.js
src/data/website-content-item/schema.js

Updated the **website-content-item** schema and resolver

[CFDP-241] Added 'openLinksNewTab' Attribute to Resolver and Schema

---

config.yml
src/data/address/data-source.js
src/data/content-item/data-source.js
src/data/event-content-item/resolver.js
src/data/event-content-item/schema.js
src/data/events/data-source.js
src/data/events/index.js
src/data/events/resolver.js
src/data/events/schema.js
src/data/features/data-source.js
src/data/index.js
src/data/schedule/data-source.js

This rework was initiated by [CFDP-367]
[CFDP-367]: https://christfellowshipchurch.atlassian.net/browse/CFDP-367

Updated Events Content Item schema

---

src/data/event-content-item/resolver.js
src/data/event-content-item/schema.js

* Added `openLinksInNewTab` attribute to `resolver` and `schema`

[CFDP-340] Events - Open Links in New Tab

---

src/data/website-feature/resolver.js
src/data/website-feature/schema.js

Added Title, Subtitle, Images to `website-feature`

[CFDP-414] website-feature Update

---

src/data/campus/data-source.js

Updated 'campus' to get all campuses by 'Order' displayed in Rock

[CFDP-439] Campus Order Update

---

src/data/event-content-item/resolver.js
src/data/event-content-item/schema.js

* Added `hideLabel` boolean attribute to `event-content-item`

[CFDP-458] hide event label

---

src/data/campus/data-source.js
src/data/event-content-item/resolver.js

* `event-content-item` can now pull schedules from the Weekend Service Schedules attribute

[CFDP-467] add campus times to events

---

config.yml
src/data/features/data-source.js

New feature allows a Content Channel in Rock to manage and reorder specific FEature Action Lists

Added Rock dynamic feed

---

src/data/campus/resolver.js

* Certain emails for the Campus Pastor's were producing a space inside of them because of the `'` in their name.
* Updated logic for generating Campus Pastor's email

[CFDP-627] fixed Campus Pastor email bug

---

config.yml
src/data/campus/data-source.js

Removed the recursion of requesting patching and requesting a default campus so that patching happens in the background and does not cause an infinite loop

Removed Recursion

---

config.yml
src/data/features/data-source.js

Rock dynamic feed with security

---

apollos_task_dev.json
apollos_task_prod.json
src/data/live-stream/data-source.js
src/data/search/data-source.js

Redis caching enhancements

---

package.json
yarn.lock

This branch has all the the `dependabot` PRs merged into it.

Dependabot check

---

src/data/features/data-source.js
src/data/index.js
src/data/prayer-request/data-source.js
src/data/prayer-request/index.js
src/data/prayer-request/resolver.js
src/data/prayer-request/schema.js

* Localized Prayer Request to add dailyPrayer endpoint
* Added DAILY_PRAYER algorithm

Apollos prayer feature

---

config.yml
src/data/content-item/resolver.js
src/data/features/data-source.js
src/data/index.js
src/data/matrix-item/__tests__/data-source.tests.js
src/data/matrix-item/data-source.js
src/data/matrix-item/index.js
src/data/metadata/data-source.js
src/data/page-builder/data-source.js
src/data/page-builder/index.js
src/data/page-builder/resolver.js
src/data/page-builder/schema.js
src/data/people/resolver.js

- In order to manage content on our location pages better, we need to create a new page builder for the location pages.
- created new `page-builder`
- added `MatrixItems`

[CFDP-804] page builder

---

src/data/defined-value/data-source.js
src/data/groups/data-source.js

Resolves the Button Label Attribute as a defined value

Returns proper Button Text

---

config.yml
src/data/content-item/data-source.js
src/data/groups/data-source.js

@jordanwade I gotta merge this right away but I just wanted you to see this so that you were aware of what updates we were making

Groups launch cleanup

---

src/data/groups/data-source.js

1. For groups that have `iCalendarContent ` this makes sure that the api is return the next occurrence. That way in the client when a user clicks `Add to calendar` the date will be the next meeting time in the future.
2. For groups that don't have `iCalendarContent ` I've added the timezone offset to be correct as well. So, if you are in EST the time the meeting starts matches what was setup in Rocks group schedule. If you are in CST and you click `Add to Calendar` the event time will be offset to account for the correct time.
3. TODO: Make sure the time shown on cards match the local timezone just like the `Add to Calendar`
If you change your computers timezone and make sure your sim updates. The group time should reflect your timezone. My says 6pm since I’m CST.

Get next group occurrence and correct timezones

---

src/data/content-item/data-source.js

This PR overrides the cursor methods for getting Content Items by a Parent or Child ID.
The method sorts the Content Items by Rock's Content Item Association `Order` as opposed to the Content Channel Item `Order`
Rock orders Content Channel Items in a Content Channel using an Order prop on the Content Channel Item. When looking at a Child/Parent relationship between Items, the order that we want to respect is no longer the Content CHANNEL `Order`, but rather the order between all Children for a given Parent. This does that.

[CFDP-956] Sorts by Content Channel Item ASSOCIATION order

---

config.yml
src/data/checkinable/data-source.js
src/data/checkinable/resolver.js
src/data/checkinable/schema.js
src/data/content-item/data-source.js
src/data/features/data-source.js
src/data/group-item/data-source.js
src/data/group-item/resolver.js
src/data/group-item/schema.js
src/data/live-stream/schema.js
src/data/people/resolver.js
src/data/people/schema.js
src/data/schedule/data-source.js

Enables pagination for people in a group. Filterable by Leaders and non-leaders
@jordanwade this should be 100% backwards compatible, but I wanted to run it by you before merging

New `people` field for GroupItem

---

config.yml
local.graphql
package.json
src/data/auth/resolver.js
src/data/checkinable/data-source.js
src/data/checkinable/resolver.js
src/data/checkinable/schema.js
src/data/content-item/data-source.js
src/data/content-item/resolver.js
src/data/event-content-item/deprecated-resolvers.js
src/data/event-content-item/resolver.js
src/data/event-content-item/schema.js
src/data/events/data-source.js
src/data/events/resolver.js
src/data/events/schema.js
src/data/features/data-source.js
src/data/group-item/data-source.js
src/data/group-item/resolver.js
src/data/group-item/schema.js
src/data/live-stream/data-source.js
src/data/live-stream/resolver.js
src/data/live-stream/schema.js
src/data/people/resolver.js
src/data/people/schema.js
src/data/schedule/data-source.js
src/data/stream-chat/index.js
src/data/stream-chat/resolver.js
src/data/stream-chat/schema.js

This PR is set up to consolidate the following changing into 1 single merge:
1. StreamChatChannel schema introduction
2. New Events Schema
3. Check In updates

The Big Merge

---

src/data/group-item/data-source.js

DO NOT display Inactive or Pending group members

Filter Groups by Active only

---

.gitignore
apollos.json
package.json
scripts/generateLocalSchema.sh
scripts/init.sh
src/data/action-algorithms/data-source.js
src/data/action-algorithms/index.js
src/data/features/data-source.js
src/data/features/resolver.js
src/data/index.js
src/server.js
yarn.lock

Updates to Apollos 1.6.0
Biggest changes coming in the form of organization of the Feature package. All references to `createGlobalId` have been moved from the Feature dataSource to individual Feature Resolvers.
There is also an app branch to go along with this update, but we need to insure that it is backwards compatible before launching.

Apollos 1.6.0

---

config.yml
src/data/content-item/data-source.js
src/data/features/data-source.js
src/data/schedule/data-source.js
src/data/utils.js

Fixes and adjustments in preparation for the 5.4.0 release

Schedule bugs

---

config.yml

Adds a feature flag `GROUP_CUSTOMIZATION` so we can safely develop the new [**Group Customization 💅**](https://3.basecamp.com/3926363/buckets/17566548/documents/3094840728) features.
Unlike other recent features, this feature flag will most likely need temporarily queried by clients via `useFeatureFlag` hook/`getFeatureFlagStatus` query, to show/hide the **Edit** button(s) as needed.
When the feature is released, we can remove the client-side checks.
There's currently no long term need for an API schema change to support Group Customization, otherwise we could integrate the feature flag check there and return `null` to clients as a way to disable it.
None currently — just sanity check the `config.yml` change.
None
N/A
**Manual QA**
> The purpose of PR Review is to _improve …

[Group Customization] Add GROUP_CUSTOMIZATION feature flag

---

src/data/group-item/data-source.js

There was an issue where Group schedules were showing up like 4 or 5 hours behind in production. Noticed that the updated time zone methods were not being used in the Group dateTime property (that's my bad. I meant to update it)
I don't _think_ that we're making any trade offs
I tested by changing my time zone on my computer and checking the display of the time was properly converted based on the selected time zone.

Use schedule parser for Group Date Time

---

src/data/live-stream/data-source.js
src/data/live-stream/resolver.js
src/data/live-stream/schema.js

Fixes an issue that happens in `liveStream.relatedNode` resolver, where a `const` value is attempted to be overwritten, causing an error:
None
1. Read code carefully
2. Run this query locally in graphql playground, with an auth header, make sure no errors or warnings in log:
```graphql
query getLiveEvents {
liveStreams {
id
isLive
relatedNode {
id
...on EventContentItem {
title
eventGroupings {
name
instances {
start
end
}
}
}
}
streamChatChannel {
channelId
}
}
}
```
**Manual QA**

[LiveStreams] Fix an issue in relatedNode resolver

---

src/data/live-stream/data-source.js
src/data/live-stream/schema.js

Updates filtering to happen AFTER storing data in Redis

---

apollos_task_dev.json
apollos_task_prod.json
src/data/matrix-item/data-source.js

Increase load part 1

---

src/data/content-item/data-source.js
src/data/redis-cache/data-source.js

Updates event cache

---

src/data/__tests__/utils.tests.js
src/data/people/resolver.js
src/data/utils.js

This PR establishes the first follow up to image caching since we first introduced Cloudinary. This image enhancement focuses on user's Profile Images.
The following compressions were included (per the available options of [Image Resizer](https://imageresizing.net/docs/v4/docs/basics)):
1. Forced size to 150x150
2. Image quality set to 70 (see documentation)
3. Convert image to jpeg
4. Crop the image when resizing
With profile images, we had 2 opportunities for image compression: at user upload, at request of the image. With this update, we decided to make the update at the API level to be a request compression.
Request a profile image from the visual gql interface and look for a url with the following query params:
`https:cloudfront.christfellowship.church/GetImage.ashx?guid=_GUID_&mode=c …

[CFDP-1067] Profile image compression

---

src/data/index.js
src/data/people/data-source.js
src/data/redis-cache/data-source.js
src/data/rock-constants/data-source.js
src/data/rock-constants/index.js

Persona caching

---

src/data/content-channel/data-source.js
src/data/content-item/data-source.js
src/data/features/data-source.js
src/data/group-item/data-source.js
src/data/redis-cache/data-source.js

Check out the commit notes, but this PR updates a couple of areas that we've found to be inefficient and adds a layer of Redis caching to them.

Cache considerations

---

config.yml
src/data/campus/data-source.js
src/data/content-item/resolver.js
src/data/features/data-source.js
src/data/group-item/data-source.js
src/data/live-stream/data-source.js
src/data/people/data-source.js
src/data/prayer-request/data-source.js
src/data/redis-cache/data-source.js
src/data/schedule/data-source.js

Additional caching
**Manual QA**

Connect feed caching

---

src/data/live-stream/data-source.js
src/data/live-stream/weekend-services.js

added service times

---

src/data/__tests__/utils.tests.js
src/data/content-item/data-source.js
src/data/live-stream/data-source.js
src/data/live-stream/resolver.js
src/data/people/resolver.js
src/data/redis-cache/data-source.js
src/data/utils.js

Fixes a bug preventing `liveStream` chat channels from fully working as expected.
It was somewhat hidden, since client side caching and/or some other ghost-ey behavior seemed to bypass the bug.
PR #158 lifted the `channelType` value from clients to the api, so things that are "chattable" can be responsible for resolving what `channelType` to use when integrating with the Stream Chat SDK/client.
There was a bug related to that (or possibly the earlier event schema changes) where the `LiveStream.getStreamChatChannel` method was not actually being invoked from the resolvers.
None
As an authenticated user with access to `LIVE_STREAM_CHAT` feature flag in graphql playground, run the following query and verify there are values for `streamChatChannel` fields:
```graphql
query getLiveContent { …
```

[LiveStream] Fix streamChatChannel resolver

---

config.yml
src/data/additional-endpoints/schema.js
src/data/index.js
src/data/link-tree/data-source.js
src/data/link-tree/index.js
src/data/link-tree/resolver.js
src/data/link-tree/schema.js
src/data/redis-cache/data-source.js

API support for the following web PR:
Create a page in the website called ChristFellowship.Church/info.
Display a list of buttons on the page pulled in from Defined Type
Returns an array of `FeatureAction`. Although we could have used the `CallToAction` type, this effort is in an attempt to begin deprecating the `CallToAction` for the more robust `FeatureAction` schema.
```
query linkTree {
linkTree {
title
action
relatedNode {
... on Url {
id
url
}
}
}
}
```
n/a
**Manual QA**

[CFDP-1134] Adds support for a Link Tree

---

src/data/group-item/data-source.js

Fix issue #194 by de-duplicating the results of `GroupItem.getMembers`, `GroupItem.getLeaders`, and `GroupItem.paginateMembersById` data-source methods.
Also ensures only _non-leaders_ are returned for `getMembers` via extra Rock API filter for `IsLeader eq false`. This was missing previously, so leaders could show as both members _and_ leaders — causing unexpected behavior.
There may be more places where duplication is possible. I updated them in the 3 most used places, but didn't thoroughly audit the potential ways users are queried.
We should also double check the total counts and pagination isn't disrupted by this change.
**A second set of eyes is highly encouraged, as this was a quick fix!**
⚠️ There is some client query or cache quirk preventing me from seeing the problematic **Vero …

[Groups] De-dupe group members/leader and people resolvers

---

config.yml
package.json
src/data/action-algorithms/data-source.js
src/data/defined-value-list/data-source.js
src/data/features/data-source.js
src/data/group-item/data-source.js
src/data/people/resolver.js
src/data/redis-cache/data-source.js
src/data/schedule/data-source.js
src/data/utils.js
yarn.lock

Revamps the entire Group Filtering system to be driven by Rock configuration
We need more explicit control and easier management of the Groups that are displayed on the digital platform
Exact tickets can be found here:
[CFDP-1136]
[CFDP-1103]
[CFDP-1077]
[CFDP-1136]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1136
[CFDP-1103]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1103
[CFDP-1077]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1077

Patch groups filtering

---

src/data/search/resolver.js
src/data/search/schema.js
src/data/search/search-index.js

Adds a `totalResults` resolver on `SearchResultsConnection` that passes along the total number of Algolia search hits for a given query.
None
Run the following query in graphql playground locally, and see how the total results for various queries changes:
**Query:**
```graphql
query searchGroups($query: SearchQueryInput!, $first: Int, $after: String) {
searchGroups(query: $query, first: $first, after: $after) {
totalResults
pageInfo {
startCursor
endCursor
}
edges {
cursor
title
node {
id
}
}
}
}
```
**Variables:**
```json
{
"query": {
"attributes": [
{
"key": "text",
"values": ["group"]
}
]
},
"first": 10
}
```
None
**Manual QA**

[Group Finder] Add SearchResultsConnection.totalResults resolver

---

src/data/group-item/data-source.js
src/data/group-item/resolver.js
src/data/group-item/schema.js
src/data/search/search-index.js

This creates a handful of new endpoints we can use to improve the search group finder experience.
This PR will make it easier for the front-end to consume necessary data needed for group finder UI.
**Manual QA**

Group finder queries

---

src/data/group-item/data-source.js

This updates the groupId to be a Rock group id instead of a Apollos Group id so this workflow actually works now.
**Manual QA**

Fix contact group leader id workflow issue

---

config.yml

Updates the Feature Flag Group Id's to the updated values that were added to Rock.
Requested from Brandi
n/a
Make sure that you are in the Group inside of Rock and test the My Groups Features to make sure you have access
n/a

[CFDP-1179] Feature Flag group Ids

---

config.yml
src/data/group-item/data-source.js
src/data/group-item/resolver.js
src/data/group-item/schema.js

This adds `meetingType` to group item and the group search and filtering. A meetingType is currently either 'In Person' or 'Online'.
| Web |
| --- |
|![image](https://user-images.githubusercontent.com/2528817/109179537-9fad7980-774f-11eb-9c8c-af4282eca6a0.png)|
**Manual QA**

Add `meetingType` to group item and search

---

src/data/content-item/data-source.js

Fixes #219 
When you don't have a `REDIS_URL`  value in your `.env`, the `ContentItem` data source still tries to create a `new Redis` — which throws a bunch of spammy warnings like:
```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
```
This PR fixes that issue.
None
Make sure your API runs requests without a bunch of those warnings ☝️ .
None
N/A
**Manual QA**
> The purpose of PR Review is to …

Fix Redis console spam

---

src/data/group-item/data-source.js

* adds a try-catch to the `getStreamChatChannel` on Groups so that an entire Group doesn't crash when an error is thrown
* todo : figure out how to resolve the error happening: user is specified in the channel but doesn't exist in Stream
**Manual QA**

[CFDP-1247] Patch : - group chat error

---

.eslintrc.js

Same PR as https://github.com/christfellowshipchurch/apollos-api/pull/245 just wanted to branch off of `apollos-2.0` instead of `master` sorry if this causes confusion. 
It was approved by @asleepingpanda

Add apollos core linting rules

---

.eslintrc.js
package.json
src/data/group-item/data-source.js
src/data/group-item/index.js
src/data/group-item/jobs.js
src/data/search/data-source.js
src/data/search/search-client.js
src/data/search/search-index.js
yarn.lock

Adds a cron job using Apollos core setup to sync/index groups to Algolia on a regular interval.
**Minor fixes/refinements (from Ryan)**
- Deletes all group records from Algolia _right_ before adding the new ones (Closes #253)
- Fixes the `preferences` method to properly fall back on default value when `titleOverride` isn't set (Fixes #254)
- Updates logging and developer friction so it's not too easy to accidentally trigger indexes locally
- Cleans up the linting in Group Item data source and the Algolia search-index files.
- Most of the "real" changes are in [these commits](https://github.com/christfellowshipchurch/apollos-api/pull/256/files/178bec509503c9949a7b478e1a208aa9fd15906f) and [these ones
](https://github.com/christfellowshipchurch/apollos-api/pull/256/files/9ee84701f3320a6615d6 …

Add group finder cron job

---

config.yml
src/data/group-preference/resolver.js
src/data/group-preference/schema.js

Adds the connection point between a Group Preference and its Notify Me Banner
```
query notifyMeBanner($preferenceId: ID!) {
notifyMeBanner(preferenceId: $preferenceId) {
title
htmlContent
}
}
```
Grab one or 2 of the Group Preference Ids and use them for the query above

Adds new Notify Me endpoint

---

config.yml

Connects the Group Leader and Resources Categories to the `/studies` pathname route
```
query getContentItem {
getNodeByPathname(pathname: "studies/married-people-for-women-only-by-shaunti-feldhahn") {
id
...soOnAndSoForth
}
}
```

Adds new /studies Content Channel

---

config.yml
src/data/group-item/data-source.js

Calculates a priority for a Group based on some keywords and priorities the return results by that

Adds `priority` ranking

---

src/data/group-item/resolver.js
src/data/utils.js

I noticed some of the images were loading pretty slowly, so I added some logic to adjust the size to a more appropriate size.

Group image processing

---

src/data/group-item/data-source.js

Fixes #274 
I didn't spend time sussing out what this looks like for the individual group index mutation.
I.e. if you try to manually index an individual group, but it's full, should it be deleted from algolia instead of updated?
Do an indexing dry run locally by using the index all groups mutation:
```graphql
mutation {
indexAllGroups(action: update, key: APOLLOS_SECRET)
}
```
No groups are currently full, so I haven't seen it work, but it should if the `getMemberStatus` logic is working as intended.
**Manual QA**

Prevent indexing full capacity groups

---

src/data/content-item/data-source.js
src/data/content-item/index.js
src/data/content-item/jobs.js
src/data/content-item/resolver.js
src/data/group-item/jobs.js
src/data/search/schema.js

Closes #263 
Adds new mutation `indexAllContent` similar to the `indexAllGroups` one. This manually triggers the data source method to delete and reindex all relevant content.
Sets up cron job to automatically index all content at certain time interval.
Also restores the `deleteJobs` method for Content and Group items, and runs it before re-creating the jobs.
Deleting the jobs before we create them on server startup/redeploy has a tradeoff. It prevents multiple job schedules when we change the cron timing — i.e. accidentally adding a _second_ indexing job at different schedule, instead of _replacing_ the first one. But it also deletes the pass/fail history since last deploy.
I spent ~20 min looking into preventing this, but didn't find an easy solve.
The other option is to _not_ delete …

Support reindexing all ContentItems in Algolia

---

src/data/action-algorithms/data-source.js

Added `labelText` attribute to all Events and Content Children algorithms.
Go to the Events page to see the custom labels.

Label text feature card

---

src/data/group-item/data-source.js

Updates filter and sort for groupResourceOptions.
**Manual QA**

Update sort and filter for group resource options

---

src/data/group-preference/data-source.js
src/data/group-preference/resolver.js
src/data/group-preference/schema.js

https://www.loom.com/share/4004f646e6594184b2b6ad03238ca383
[CFDP-1331]
Web App: https://github.com/christfellowshipchurch/web-app-v2/pull/282 
[CFDP-1331]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1331

Group notify me mutation

---

src/data/action-algorithms/data-source.js
src/data/event-content-item/resolver.js
src/data/events/data-source.js

* This moves the `labelText` resolver logic over to the data-source so that it can be re-used in other areas
* Properly resolves the `labelText` within action algorithms
The `contentChildrenAlgorithm` will check for an EventContentItem type before running the `Event.createLabelText` in order to try and save on some performance
Load up the events feature feed and look for the "Caleb's Test Event"
[CFDP-1518]
[Web App](https://github.com/christfellowshipchurch/web-app-v2/pull/291)
[CFDP-1518]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1518

Patch event label text

---

src/data/stream-chat/data-source.js

Added subtitle with channel name to chat Notifications

Added subtitle with channel name to chat Notifications

---

src/data/stream-chat/data-source.js

Related Client Side update:
[Mobile App](https://github.com/christfellowshipchurch/apollos-app/pull/236)

Split notifcation payload
